project_name: aws-whoami
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - arm64
      - amd64
    main: ./aws-whoami
nfpms:
  - package_name: aws-whoami
    vendor: Ben Kehoe
    homepage: https://github.com/benkehoe/aws-whoami-golang
    maintainer: Ben Kehoe
    description: A tool to show what AWS account and identity you're using.
    formats: [ deb ]
brews:
  - name: aws-whoami
    tap:
      owner: benkehoe
      name: homebrew-tap
      token: '{{ .Env.GORELEASER_HOMEBREW_TAP_TOKEN }}'
    commit_author:
      name: Ben Kehoe
      email: ben@kehoe.io
    homepage: https://github.com/benkehoe/aws-whoami-golang
    description: A tool to show what AWS account and identity you're using.
archives:
  - format: tar.gz
    # this name template makes the OS and Arch compatible with the results of uname.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

# The lines beneath this are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj
